export const COUNTRIES = [
  { name: "United States", code: "+1", iso: "US", flag: "🇺🇸" },
  { name: "India", code: "+91", iso: "IN", flag: "🇮🇳" },
  { name: "United Kingdom", code: "+44", iso: "GB", flag: "🇬🇧" },
  { name: "Germany", code: "+49", iso: "DE", flag: "🇩🇪" },
  { name: "France", code: "+33", iso: "FR", flag: "🇫🇷" },
  { name: "Japan", code: "+81", iso: "JP", flag: "🇯🇵" },
  { name: "Brazil", code: "+55", iso: "BR", flag: "🇧🇷" },
  { name: "China", code: "+86", iso: "CN", flag: "🇨🇳" },
];

export const MOCK_NUMBERS = [
  {
    id: "1",
    number: "+1 202 555 0124",
    country: "United States",
    countryCode: "US",
    provider: "Verizon",
    status: "online",
    flag: "🇺🇸",
  },
  { id: "2", number: "+1 312 555 0199", country: "United States", countryCode: "US", provider: "AT&T", status: "online", flag: "🇺🇸" },
  {
    id: "3",
    number: "+1 415 555 0145",
    country: "United States",
    countryCode: "US",
    provider: "T-Mobile",
    status: "offline",
    flag: "🇺🇸",
  },
  {
    id: "4",
    number: "+1 646 555 0178",
    country: "United States",
    countryCode: "US",
    provider: "Verizon",
    status: "online",
    flag: "🇺🇸",
  },
  {
    id: "5",
    number: "+1 213 555 0132",
    country: "United States",
    countryCode: "US",
    provider: "Sprint",
    status: "online",
    flag: "🇺🇸",
  },
  { id: "6", number: "+1 718 555 0111", country: "United States", countryCode: "US", provider: "AT&T", status: "online", flag: "🇺🇸" },
  {
    id: "7",
    number: "+1 305 555 0188",
    country: "United States",
    countryCode: "US",
    provider: "T-Mobile",
    status: "online",
    flag: "🇺🇸",
  },
  {
    id: "8",
    number: "+1 617 555 0102",
    country: "United States",
    countryCode: "US",
    provider: "Verizon",
    status: "offline",
    flag: "🇺🇸",
  },

  { id: "9", number: "+91 98765 43210", country: "India", countryCode: "IN", provider: "Jio", status: "online", flag: "🇮🇳" },
  { id: "10", number: "+91 81234 56789", country: "India", countryCode: "IN", provider: "Airtel", status: "online", flag: "🇮🇳" },
  { id: "11", number: "+91 70123 45678", country: "India", countryCode: "IN", provider: "VI", status: "offline", flag: "🇮🇳" },
  { id: "12", number: "+91 99887 76655", country: "India", countryCode: "IN", provider: "Jio", status: "online", flag: "🇮🇳" },
  { id: "13", number: "+91 91234 88776", country: "India", countryCode: "IN", provider: "Airtel", status: "online", flag: "🇮🇳" },
  { id: "14", number: "+91 96543 21098", country: "India", countryCode: "IN", provider: "BSNL", status: "online", flag: "🇮🇳" },
  { id: "15", number: "+91 88776 65544", country: "India", countryCode: "IN", provider: "Jio", status: "online", flag: "🇮🇳" },
  { id: "16", number: "+91 75544 33221", country: "India", countryCode: "IN", provider: "VI", status: "online", flag: "🇮🇳" },
  { id: "17", number: "+91 90011 22334", country: "India", countryCode: "IN", provider: "Airtel", status: "offline", flag: "🇮🇳" },
  { id: "18", number: "+91 82233 44556", country: "India", countryCode: "IN", provider: "Jio", status: "online", flag: "🇮🇳" },

  { id: "19", number: "+44 7700 900123", country: "United Kingdom", countryCode: "GB", provider: "EE", status: "online", flag: "🇬🇧" },
  { id: "20", number: "+44 7412 345678", country: "United Kingdom", countryCode: "GB", provider: "O2", status: "online", flag: "🇬🇧" },
  {
    id: "21",
    number: "+44 7911 123456",
    country: "United Kingdom",
    countryCode: "GB",
    provider: "Vodafone",
    status: "online",
    flag: "🇬🇧",
  },
  {
    id: "22",
    number: "+44 7300 555666",
    country: "United Kingdom",
    countryCode: "GB",
    provider: "Three",
    status: "offline",
    flag: "🇬🇧",
  },
  { id: "23", number: "+44 7824 999888", country: "United Kingdom", countryCode: "GB", provider: "EE", status: "online", flag: "🇬🇧" },
  { id: "24", number: "+44 7555 111222", country: "United Kingdom", countryCode: "GB", provider: "O2", status: "online", flag: "🇬🇧" },

  { id: "25", number: "+49 151 23456789", country: "Germany", countryCode: "DE", provider: "Telekom", status: "online", flag: "🇩🇪" },
  { id: "26", number: "+49 160 98765432", country: "Germany", countryCode: "DE", provider: "Vodafone", status: "online", flag: "🇩🇪" },
  { id: "27", number: "+49 176 11223344", country: "Germany", countryCode: "DE", provider: "O2", status: "online", flag: "🇩🇪" },
  { id: "28", number: "+49 152 55443322", country: "Germany", countryCode: "DE", provider: "Telekom", status: "offline", flag: "🇩🇪" },
  { id: "29", number: "+49 171 88776655", country: "Germany", countryCode: "DE", provider: "Vodafone", status: "online", flag: "🇩🇪" },
  { id: "30", number: "+49 155 44332211", country: "Germany", countryCode: "DE", provider: "O2", status: "online", flag: "🇩🇪" },
  { id: "31", number: "+49 162 66778899", country: "Germany", countryCode: "DE", provider: "Telekom", status: "online", flag: "🇩🇪" },

  { id: "32", number: "+33 6 12 34 56 78", country: "France", countryCode: "FR", provider: "Orange", status: "online", flag: "🇫🇷" },
  { id: "33", number: "+33 7 88 99 00 11", country: "France", countryCode: "FR", provider: "SFR", status: "online", flag: "🇫🇷" },
  { id: "34", number: "+33 6 55 44 33 22", country: "France", countryCode: "FR", provider: "Bouygues", status: "online", flag: "🇫🇷" },
  { id: "35", number: "+33 7 11 22 33 44", country: "France", countryCode: "FR", provider: "Free", status: "offline", flag: "🇫🇷" },
  { id: "36", number: "+33 6 00 11 22 33", country: "France", countryCode: "FR", provider: "Orange", status: "online", flag: "🇫🇷" },
  { id: "37", number: "+33 7 44 55 66 77", country: "France", countryCode: "FR", provider: "SFR", status: "online", flag: "🇫🇷" },
  { id: "38", number: "+33 6 22 33 44 55", country: "France", countryCode: "FR", provider: "Bouygues", status: "online", flag: "🇫🇷" },
  { id: "39", number: "+33 7 99 88 77 66", country: "France", countryCode: "FR", provider: "Free", status: "online", flag: "🇫🇷" },
  { id: "40", number: "+33 6 11 33 55 77", country: "France", countryCode: "FR", provider: "Orange", status: "offline", flag: "🇫🇷" },

  { id: "41", number: "+81 90 1234 5678", country: "Japan", countryCode: "JP", provider: "NTT Docomo", status: "online", flag: "🇯🇵" },
  { id: "42", number: "+81 80 9876 5432", country: "Japan", countryCode: "JP", provider: "SoftBank", status: "online", flag: "🇯🇵" },
  { id: "43", number: "+81 70 1122 3344", country: "Japan", countryCode: "JP", provider: "au (KDDI)", status: "online", flag: "🇯🇵" },
  {
    id: "44",
    number: "+81 90 5544 3322",
    country: "Japan",
    countryCode: "JP",
    provider: "Rakuten Mobile",
    status: "offline",
    flag: "🇯🇵",
  },
  { id: "45", number: "+81 80 0011 2233", country: "Japan", countryCode: "JP", provider: "SoftBank", status: "online", flag: "🇯🇵" },

  { id: "46", number: "+55 11 98765-4321", country: "Brazil", countryCode: "BR", provider: "Vivo", status: "online", flag: "🇧🇷" },
  { id: "47", number: "+55 21 91234-5678", country: "Brazil", countryCode: "BR", provider: "Claro", status: "online", flag: "🇧🇷" },
  { id: "48", number: "+55 31 97766-5544", country: "Brazil", countryCode: "BR", provider: "TIM", status: "online", flag: "🇧🇷" },
  { id: "49", number: "+55 41 95544-3322", country: "Brazil", countryCode: "BR", provider: "Oi", status: "offline", flag: "🇧🇷" },
  { id: "50", number: "+55 51 91122-3344", country: "Brazil", countryCode: "BR", provider: "Vivo", status: "online", flag: "🇧🇷" },
  { id: "51", number: "+55 61 98877-6655", country: "Brazil", countryCode: "BR", provider: "Claro", status: "online", flag: "🇧🇷" },
  { id: "52", number: "+55 71 94433-2211", country: "Brazil", countryCode: "BR", provider: "TIM", status: "online", flag: "🇧🇷" },
  { id: "53", number: "+55 81 92233-4455", country: "Brazil", countryCode: "BR", provider: "Vivo", status: "online", flag: "🇧🇷" },

  {
    id: "54",
    number: "+86 138 1234 5678",
    country: "China",
    countryCode: "CN",
    provider: "China Mobile",
    status: "online",
    flag: "🇨🇳",
  },
  {
    id: "55",
    number: "+86 186 9876 5432",
    country: "China",
    countryCode: "CN",
    provider: "China Unicom",
    status: "online",
    flag: "🇨🇳",
  },
  {
    id: "56",
    number: "+86 133 1122 3344",
    country: "China",
    countryCode: "CN",
    provider: "China Telecom",
    status: "online",
    flag: "🇨🇳",
  },
  {
    id: "57",
    number: "+86 150 5544 3322",
    country: "China",
    countryCode: "CN",
    provider: "China Mobile",
    status: "offline",
    flag: "🇨🇳",
  },
  {
    id: "58",
    number: "+86 189 0011 2233",
    country: "China",
    countryCode: "CN",
    provider: "China Telecom",
    status: "online",
    flag: "🇨🇳",
  },
];

// Randomly select 8 online numbers for home page display
export const HOME_MOCK_NUMBERS = MOCK_NUMBERS.filter((num) => num.status === "online").slice(0, 8);

export const MESSAGES = {
  US: [
    {
      id: 1,
      co: "Google",
      txt: "G-829103 is your Google verification code. Don't share this code with anyone; Google will never call and ask for it.",
    },
    {
      id: 2,
      co: "WhatsApp",
      txt: "Your WhatsApp code: 123-456. You can also tap on this link to verify your device: v.whatsapp.com/123456. Don't share this code.",
    },
    {
      id: 3,
      co: "Chase",
      txt: "Chase: Your one-time passcode for the login attempt ending in 4492 is 882910. Do not share this code. We will never call to ask for it.",
    },
    { id: 4, co: "Instagram", txt: "<#> 551029 is your Instagram code. Don't share it. SIY732jsh2" },
    {
      id: 5,
      co: "Amazon",
      txt: "443210 is your Amazon OTP. Do not share this code with anyone. Amazon will never call or text you to ask for this code.",
    },
    { id: 6, co: "Apple", txt: "Your Apple ID Code is: 772109. Don't share it with anyone. @apple.com #772109 %apple.id" },
    {
      id: 7,
      co: "LinkedIn",
      txt: "Your LinkedIn verification code is 449102. This code expires in 10 minutes. Please do not reply to this message.",
    },
    {
      id: 8,
      co: "Microsoft",
      txt: "Use 882104 as Microsoft account security code. If you didn't request this code, you can safely ignore this message.",
    },
    {
      id: 9,
      co: "Uber",
      txt: "Uber: 5592 is your verification code. Never share this code. If you didn't request this, reply STOP to unsubscribe.",
    },
    { id: 10, co: "Netflix", txt: "Your Netflix verification code is 338102. This code will expire in 15 minutes. Happy streaming!" },
    {
      id: 11,
      co: "PayPal",
      txt: "PayPal: Your security code is 002931. Your code expires in 5 minutes. Please don't reply to this message.",
    },
    { id: 12, co: "Snapchat", txt: "Snapchat Code: 442910. Happy Snapping! Don't share this code with anyone else." },
    {
      id: 13,
      co: "Discord",
      txt: "Your Discord verification code is: 552910. This code is valid for 10 minutes. If you did not request this, please secure your account.",
    },
    {
      id: 14,
      co: "Airbnb",
      txt: "Your Airbnb verification code is 7721. If you didn't request this, let us know at airbnb.com/security.",
    },
    {
      id: 15,
      co: "Spotify",
      txt: "Use 992188 to log in to your Spotify account. This code expires in 10 minutes. @spotify.com #992188",
    },
    {
      id: 16,
      co: "Venmo",
      txt: "Venmo: Your verification code is 449210. It expires in 5 minutes. Do not share this code. Venmo will never ask for it.",
    },
    {
      id: 17,
      co: "TikTok",
      txt: "[TikTok] 992104 is your verification code. This code is used for account registration or login. Do not share it with others.",
    },
    {
      id: 18,
      co: "DoorDash",
      txt: "DoorDash: 1102 is your access code. It expires in 5 minutes. Please enter it to verify your account.",
    },
    {
      id: 19,
      co: "Wells Fargo",
      txt: "Wells Fargo: 441029 is your access code. Valid for 10 minutes. Do not share this code with anyone.",
    },
    {
      id: 20,
      co: "Instacart",
      txt: "Instacart: Your verification code is 882910. Don't share this code. We'll never call to ask for it.",
    },
    { id: 21, co: "Twitter", txt: "Your Twitter confirmation code is 882910. Please enter this code to verify your phone number." },
    { id: 22, co: "Slack", txt: "Your Slack confirmation code: 332-910. Enter this code in the app to finish signing in." },
    { id: 23, co: "Tinder", txt: "Your Tinder code is 112093. Don't share it. @tinder.com #112093" },
    {
      id: 24,
      co: "Bank of America",
      txt: "Bank of America: Use 772910 to verify your identity. We'll never call or text to ask for this code.",
    },
    { id: 25, co: "Pinterest", txt: "Pinterest: 4429 is your confirmation code. Use it to verify your account." },
    {
      id: 26,
      co: "Twitch",
      txt: "Your Twitch verification code is 449102. If you did not request this, please change your password.",
    },
    { id: 27, co: "Zoom", txt: "Your Zoom verification code is 110293. This code expires in 10 minutes. Don't share it." },
    { id: 28, co: "Adobe", txt: "Your Adobe ID verification code is 881023. If you didn't request this code, ignore this message." },
    { id: 29, co: "Lyft", txt: "Your Lyft code is 3310. Don't share it with anyone. @lyft.com #3310" },
    { id: 30, co: "GitHub", txt: "[GitHub] Your two-factor authentication code is 449102. This code will expire in 10 minutes." },
    {
      id: 31,
      co: "Coinbase",
      txt: "Your Coinbase verification code is 112093. If you did not request this code, secure your account at coinbase.com/security.",
    },
    { id: 32, co: "Stripe", txt: "Stripe: 552910 is your login code. It expires in 5 minutes. Do not share this code with anyone." },
    { id: 33, co: "Walmart", txt: "Walmart: 552910 is your security code. Use this to verify your login attempt." },
    { id: 34, co: "Target", txt: "Target: 882910 is your security code. Enter it on our site to proceed." },
    { id: 35, co: "Etsy", txt: "Your Etsy verification code is 772109. If you didn't request this, let us know." },
    { id: 36, co: "Hinge", txt: "Hinge code: 4491. Let's get started! Never share your Hinge code with others." },
    { id: 37, co: "Bumble", txt: "Bumble: 552910 is your login code. It's valid for 10 minutes. Happy buzzing!" },
    { id: 38, co: "Postmates", txt: "Postmates: 9912 is your security code. Never share this with anyone." },
    { id: 39, co: "Robinhood", txt: "Robinhood: 110293 is your verification code. It is valid for 5 minutes. Don't share this." },
    { id: 40, co: "Best Buy", txt: "Best Buy: 882910 is your verification code. Use it to complete your login." },
    { id: 41, co: "Capital One", txt: "Capital One: Use 552910 to verify your identity. We'll never call to ask for this code." },
    { id: 42, co: "American Express", txt: "Amex: Your verification code is 110293. This code expires in 10 minutes." },
    { id: 43, co: "Dropbox", txt: "Dropbox: 552910 is your security code. If you didn't request this, change your password." },
    { id: 44, co: "Reddit", txt: "Reddit: Your verification code is 441092. Welcome back!" },
    { id: 45, co: "Steam", txt: "Steam Guard: Your account verification code is 77B2X. Do not share this code." },
    { id: 46, co: "Battle.net", txt: "Blizzard: Your verification code is 552910. Enter this code to verify your identity." },
    { id: 47, co: "Epic Games", txt: "Epic Games: Your two-factor authentication code is 441092. Please enter this code to sign in." },
    { id: 48, co: "PlayStation", txt: "PSN: Your verification code is 110293. Enter it on your console to proceed." },
    { id: 49, co: "Xbox", txt: "Xbox: 445-667 is your security code. Don't share this code." },
    { id: 50, co: "Nintendo", txt: "Your Nintendo Account verification code is 882910. This code will expire in 20 minutes." },
    { id: 51, co: "Hulu", txt: "Hulu: 772-109 is your verification code. Happy streaming!" },
    { id: 52, co: "Disney+", txt: "Your Disney+ verification code is 882910. This code is valid for 15 minutes." },
    { id: 53, co: "HBO Max", txt: "HBO: 112-233 is your verification code. Enter this to finish signing in." },
    { id: 54, co: "Paramount+", txt: "Paramount+: 112-233 code. Use this to verify your account." },
    { id: 55, co: "Peacock", txt: "Peacock: 445-667 is your code. Don't share it." },
    { id: 56, co: "Verizon", txt: "Verizon: 110293 is your account code. We will never call to ask for this." },
    { id: 57, co: "AT&T", txt: "AT&T: Your security code is 772109. Keep it secure." },
    { id: 58, co: "T-Mobile", txt: "T-Mobile: 882910 is your verification code. Don't share this code." },
    { id: 59, co: "FedEx", txt: "Your FedEx delivery code is 1102. Enter this to verify your package redirect." },
    { id: 60, co: "UPS", txt: "UPS My Choice: 8829 is your verification code. Valid for 10 minutes." },
  ],
  IN: [
    {
      id: 101,
      co: "HDFC Bank",
      txt: "882910 is the OTP for your txn of INR 4500.00 at ZOMATO with HDFC Bank Card ending 1234. Valid for 5 mins. Do not share.",
    },
    {
      id: 102,
      co: "PhonePe",
      txt: "662910 is your OTP for PhonePe. For security reasons, do not share this with anyone. PhonePe never asks for your OTP.",
    },
    {
      id: 103,
      co: "Aadhaar",
      txt: "441092 is the OTP for your Aadhaar verification. Do not share this with anyone. UIDAI never calls for OTP.",
    },
    {
      id: 104,
      co: "Paytm",
      txt: "OTP to login to your Paytm account is 110293. This is only valid for 10 minutes. Do not share this with anyone.",
    },
    {
      id: 105,
      co: "Google",
      txt: "G-829103 आपका Google सत्यापन कोड है। किसी को न बताएं। Google कभी भी आपके कोड के लिए कॉल नहीं करेगा।",
    },
    { id: 106, co: "Zomato", txt: "112233 is your OTP for Zomato. Use this to verify your mobile number. Valid for 3 minutes." },
    {
      id: 107,
      co: "Swiggy",
      txt: "552910 is your Swiggy OTP. Please do not share this code with anyone, including Swiggy delivery partners.",
    },
    { id: 108, co: "Flipkart", txt: "110293 is your Flipkart verification code. Valid for 5 minutes. Happy Shopping!" },
    {
      id: 109,
      co: "ICICI Bank",
      txt: "OTP for your ICICI Bank txn of Rs. 1500 is 441092. Valid for 180 seconds. Do not share with anyone.",
    },
    { id: 110, co: "Myntra", txt: "110293 is your Myntra verification code. Valid for 5 minutes. Let's get styling!" },
    {
      id: 111,
      co: "SBI",
      txt: "SBI: 882910 is your OTP for the transaction of INR 250.00. Do not share OTP with anyone for security.",
    },
    { id: 112, co: "Tata Neu", txt: "441092 is your login OTP for Tata Neu. Valid for 5 minutes. Join the rewards experience today!" },
    { id: 113, co: "Jio", txt: "Your OTP for Jio login is 772109. Valid for 10 mins. Share this only on the MyJio app." },
    { id: 114, co: "Airtel", txt: "Airtel: 552910 is your OTP for account login. Never share your OTP with anyone." },
    { id: 115, co: "Ola", txt: "Ola: 110293 is your verification code. Use this to sign in to your Ola account." },
    {
      id: 116,
      co: "Uber India",
      txt: "Uber: 8829 is your verification code. Never share this code. Uber will never call you for this.",
    },
    { id: 117, co: "Axis Bank", txt: "Axis Bank: 441092 is the OTP to authorize your online txn of INR 1200.00. Do not share." },
    { id: 118, co: "Amazon India", txt: "772109 is your Amazon OTP. Only use this on the official app. Do not share this code." },
    { id: 119, co: "Zivame", txt: "Zivame: Your verification code is 552910. Use this to complete your order." },
    { id: 120, co: "Nykaa", txt: "Nykaa: 110293 is your login OTP. Shop for your favorite beauty products now!" },
    { id: 121, co: "BigBasket", txt: "Your BigBasket login code is 882910. Do not share this code." },
    { id: 122, co: "Blinkit", txt: "Blinkit: 441092 is your login OTP. Your groceries are minutes away!" },
    { id: 123, co: "Zepto", txt: "Zepto: 772109 is your OTP. Delivering fresh in 10 minutes!" },
    { id: 124, co: "IndiGo", txt: "IndiGo: 552910 is your flight booking verification code. Happy travels!" },
    { id: 125, co: "Air India", txt: "Air India: 110293 is your security code for account access." },
    { id: 126, co: "Kotak Mahindra", txt: "Kotak Bank: 882910 is your OTP for the transaction. Do not share this with anyone." },
    { id: 127, co: "LIC India", txt: "LIC: Your OTP for premium payment is 441092. Secure your future today." },
    { id: 128, co: "IRCTC", txt: "IRCTC: 772109 is the OTP for your ticket booking. Do not share with anyone." },
    { id: 129, co: "MakeMyTrip", txt: "MMT: 552910 is your login OTP. Start planning your next holiday!" },
    { id: 130, co: "ClearTrip", txt: "ClearTrip: 110293 is your verification code. Safe travels!" },
    { id: 131, co: "Urban Company", txt: "UC: 882910 is your verification code for the service booking." },
    { id: 132, co: "Dunzo", txt: "Dunzo: 441092 is your login code. We fetch, you relax!" },
    { id: 133, co: "Cred", txt: "CRED: 772109 is your secret OTP for login. Rewarding your credit habits." },
    { id: 134, co: "Groww", txt: "Groww: 552910 is your OTP to authorize the trade. Invest safely." },
    { id: 135, co: "Upstox", txt: "Upstox: 110293 is your verification code for account login." },
    { id: 136, co: "Zerodha", txt: "Kite by Zerodha: 882910 is your OTP for the transaction. Keep it private." },
    { id: 137, co: "Lenskart", txt: "Lenskart: 441092 is your OTP. Try our 3D frames now!" },
    { id: 138, co: "FirstCry", txt: "FirstCry: 772109 is your verification code. Shopping for your little one?" },
    { id: 139, co: "Ajio", txt: "AJIO: 552910 is your login OTP. Fashion at your fingertips." },
    { id: 140, co: "MyGlamm", txt: "MyGlamm: 110293 is your OTP for beauty rewards." },
    { id: 141, co: "Bewakoof", txt: "Bewakoof: 882910 is your OTP. Stay quirky, stay cool!" },
    { id: 142, co: "Boat", txt: "boAt: 441092 is your verification code. Plug into nirvana." },
    { id: 143, co: "Noise", txt: "Noise: 772109 is your login OTP for your smartwatch sync." },
    { id: 144, co: "BookMyShow", txt: "BMS: 552910 is your OTP for movie ticket booking. Enjoy the show!" },
    { id: 145, co: "PVR", txt: "PVR Cinemas: 110293 is your security code for loyalty login." },
    { id: 146, co: "Oyo Rooms", txt: "OYO: 882910 is your login code. Find a room anywhere." },
    { id: 147, co: "Treebo", txt: "Treebo: 441092 is your verification code for the stay." },
    { id: 148, co: "PolicyBazaar", txt: "PolicyBazaar: 772109 is your OTP to compare plans." },
    { id: 149, co: "Paisabazaar", txt: "Paisabazaar: 552910 is your code for the credit score check." },
    { id: 150, co: "MagicBricks", txt: "MagicBricks: 110293 is your OTP for property search." },
    { id: 151, co: "Housing.com", txt: "Housing: 882910 is your verification code for account access." },
    { id: 152, co: "NoBroker", txt: "NoBroker: 441092 is your OTP to rent without brokerage." },
    { id: 153, co: "Byju's", txt: "BYJU'S: 772109 is your verification code for the learning app." },
    { id: 154, co: "Unacademy", txt: "Unacademy: 552910 is your OTP to start learning today." },
    { id: 155, co: "Physics Wallah", txt: "PW: 110293 is your verification code. Padlo chahe kahi se!" },
    { id: 156, co: "Vedantu", txt: "Vedantu: 882910 is your code for the live class." },
    { id: 157, co: "Doubtnut", txt: "Doubtnut: 441092 is your verification code for the doubt clearing." },
    { id: 158, co: "PharmEasy", txt: "PharmEasy: 772109 is your OTP. Medicines delivered home." },
    { id: 159, co: "Tata 1mg", txt: "1mg: 552910 is your verification code. Your health partner." },
    { id: 160, co: "Apollo 247", txt: "Apollo: 110293 is your OTP for the doctor consultation." },
  ],
  GB: [
    {
      id: 201,
      co: "HSBC",
      txt: "HSBC: Use 552910 to authorize your request. We will never call to ask for this code. If you didn't request this, call us immediately.",
    },
    { id: 202, co: "Deliveroo", txt: "Your Deliveroo verification code is 441092. It expires in 5 minutes. Enjoy your meal!" },
    { id: 203, co: "NHS", txt: "Your NHS login security code is 110293. Do not share this with anyone." },
    {
      id: 204,
      co: "Barclays",
      txt: "Barclays: Use code 772109 to verify your mobile number. Never share this code with anyone else.",
    },
    { id: 205, co: "Tesco", txt: "Your Tesco verification code is 882910. Use this to complete your order." },
    { id: 206, co: "Sky", txt: "Your Sky verification code is 552910. Please enter it on the sign-in screen." },
    { id: 207, co: "Lloyds Bank", txt: "Lloyds: Use 110293 to confirm your payment. Never share this code with anyone else." },
    { id: 208, co: "Asos", txt: "Your ASOS verification code is 882910. Happy shopping!" },
    { id: 209, co: "Monzo", txt: "Monzo: Use 110293 to finish signing in to your app. Don't share this code with anyone." },
    { id: 210, co: "Argos", txt: "Your Argos code is 882910. Enter it now to verify your mobile number." },
    { id: 211, co: "O2", txt: "O2: Your security code is 441092. Don't share it, even with O2 staff." },
    { id: 212, co: "NatWest", txt: "NatWest: 772109 is your security code for the login attempt. Do not share." },
    { id: 213, co: "Royal Mail", txt: "Royal Mail: Your code to redirect your delivery is 552910. Valid for 15 minutes." },
    { id: 214, co: "Santander UK", txt: "Santander: 110293 is your one-time passcode for your online banking. Never share it." },
    { id: 215, co: "EE", txt: "EE: Your verification code is 882910. Please enter it in the My EE app." },
    { id: 216, co: "Vodafone UK", txt: "Vodafone: Your security code is 441092. Do not share this with anyone." },
    { id: 217, co: "Marks & Spencer", txt: "M&S: Your login code is 772109. Enjoy your shopping experience!" },
    { id: 218, co: "Sainsbury's", txt: "Sainsbury's: Your verification code is 552910 for your Groceries account." },
    { id: 219, co: "Just Eat", txt: "Just Eat: 110293 is your security code. Your food is on its way!" },
    { id: 220, co: "Nationwide", txt: "Nationwide: Use 882910 to verify your identity. We'll never call to ask for this." },
    { id: 221, co: "Co-op", txt: "Co-op: Your membership login code is 441092. Enter it now to access rewards." },
    { id: 222, co: "Boots", txt: "Boots: Your Advantage Card login code is 772109. Valid for 10 minutes." },
    { id: 223, co: "Currys", txt: "Currys: 552910 is your verification code for your tech order." },
    { id: 224, co: "John Lewis", txt: "John Lewis: Your security code is 110293. Welcome back!" },
    { id: 225, co: "Next", txt: "Next: Your verification code is 882910. Shop the latest fashion now." },
    { id: 226, co: "TUI UK", txt: "TUI: Your holiday booking verification code is 441092." },
    { id: 227, co: "EasyJet", txt: "EasyJet: 772109 is your security code for account access. Have a great flight!" },
    { id: 228, co: "British Airways", txt: "BA: Your Executive Club login code is 552910. Valid for 15 minutes." },
    { id: 229, co: "Trainline", txt: "Trainline: 110293 is your verification code. Journey on!" },
    { id: 230, co: "Admiral", txt: "Admiral: Your insurance portal login code is 882910." },
    { id: 231, co: "Aviva", txt: "Aviva: Use 441092 to verify your identity. Do not share this code." },
    { id: 232, co: "Bupa", txt: "Bupa: Your health portal verification code is 772109." },
    { id: 233, co: "Starling Bank", txt: "Starling: 552910 is your login code. Never share this with anyone." },
    { id: 234, co: "Metro Bank", txt: "Metro Bank: Your verification code is 110293. Valid for 5 minutes." },
    { id: 235, co: "Standard Chartered", txt: "StanChart: 882910 is your OTP for the transaction. Do not disclose." },
    { id: 236, co: "HMRC", txt: "HMRC: Your access code is 441092. This is valid for 15 minutes. Do not share." },
    { id: 237, co: "GOV.UK", txt: "GOV.UK: Your security code is 772109 for the Verify service." },
    { id: 238, co: "Auto Trader", txt: "Auto Trader: 552910 is your login code. Find your next car today." },
    { id: 239, co: "Rightmove", txt: "Rightmove: Your verification code is 110293. Home hunting starts here." },
    { id: 240, co: "Zoopla", txt: "Zoopla: 882910 is your security code for account login." },
    { id: 241, co: "Gumtree", txt: "Gumtree: Your verification code is 441092. Buy and sell locally." },
    { id: 242, co: "Nectar", txt: "Nectar: 772109 is your code to access your points and rewards." },
    { id: 243, co: "Waitrose", txt: "Waitrose: Your login code is 552910. Quality food delivered." },
    { id: 244, co: "Iceland", txt: "Iceland: 110293 is your verification code for your frozen food order." },
    { id: 245, co: "Greggs", txt: "Greggs: Your rewards login code is 882910. Enjoy your pasty!" },
    { id: 246, co: "Nando's", txt: "Nando's: Your verification code is 441092. Get your PERi-PERi fix." },
    { id: 247, co: "Wagamama", txt: "Wagamama: 772109 is your security code for the soul-food order." },
    { id: 248, co: "PizzaExpress", txt: "PizzaExpress: Your login code is 552910. Great pizza, good times." },
    { id: 249, co: "Vue Cinemas", txt: "Vue: 110293 is your verification code. See you at the movies!" },
    { id: 250, co: "Odeon", txt: "Odeon: Your security code is 882910 for the ticket booking." },
    { id: 251, co: "Cineworld", txt: "Cineworld: 441092 is your verification code. Enjoy the film!" },
    { id: 252, co: "Bet365", txt: "Bet365: Your login code is 772109. Please gamble responsibly." },
    { id: 253, co: "William Hill", txt: "William Hill: 552910 is your verification code. Never share your details." },
    { id: 254, co: "Coral", txt: "Coral: 110293 is your security code for account access." },
    { id: 255, co: "Ladbrokes", txt: "Ladbrokes: Your verification code is 882910. Valid for 10 minutes." },
    { id: 256, co: "Paddy Power", txt: "Paddy Power: 441092 is your login code. Don't share with anyone." },
    { id: 257, co: "Deliveroo Rider", txt: "Deliveroo: 772109 is your rider login code. Safe riding!" },
    { id: 258, co: "Uber Eats UK", txt: "Uber Eats: 552910 is your verification code. Your order is being prepped." },
    { id: 259, co: "Zego", txt: "Zego: Your insurance login code is 110293. You're covered." },
    { id: 260, co: "Amazon UK", txt: "Amazon: 882910 is your OTP. Only use this on the official app. Don't share." },
  ],
  BR: [
    { id: 301, co: "Nubank", txt: "Nubank: Use o código 772109 para autorizar sua transferência. Não informe esse código a ninguém." },
    {
      id: 302,
      co: "Mercado Livre",
      txt: "Mercado Livre: Seu código de segurança é 110293. Não o compartilhe com ninguém por nenhum motivo.",
    },
    { id: 303, co: "PicPay", txt: "Seu código PicPay é 882910. Use para validar seu acesso e não o informe a terceiros." },
    { id: 304, co: "iFood", txt: "Seu código de login iFood é 882910. Não compartilhe este código. Bom apetite!" },
    { id: 305, co: "Banco Inter", txt: "Inter: Utilize o código 110293 para confirmar sua transação no App. Válido por 5 minutos." },
    { id: 306, co: "Caixa", txt: "Caixa: Seu código de segurança para o acesso é 772109. Não compartilhe este código." },
    { id: 307, co: "Magazine Luiza", txt: "Magalu: Seu código de confirmação é 552910. Não o compartilhe com ninguém. Boas compras!" },
    {
      id: 308,
      co: "Banco do Brasil",
      txt: "BB: Informe o codigo 110293 para confirmar sua operacao. O BB nunca solicita sua senha por telefone.",
    },
    { id: 309, co: "Itaú", txt: "Itau: O codigo para confirmar sua operacao e 882910. Nunca compartilhe este codigo com ninguem." },
    { id: 310, co: "Bradesco", txt: "Bradesco: Utilize o dispositivo de seguranca e informe o codigo 441092 para prosseguir." },
    {
      id: 311,
      co: "Santander BR",
      txt: "Santander: Seu codigo de seguranca e 772109. Nao compartilhe este codigo por nenhum motivo.",
    },
    { id: 312, co: "PagSeguro", txt: "PagSeguro: Use o codigo 552910 para validar sua transacao. Nao informe o codigo a terceiros." },
    { id: 313, co: "C6 Bank", txt: "C6 Bank: Seu codigo de verificacao e 110293. Utilize-o para completar seu acesso no App." },
    { id: 314, co: "Stone", txt: "Stone: Use o codigo 882910 para acessar sua conta. Nao compartilhe este codigo com ninguem." },
    { id: 315, co: "Claro BR", txt: "Claro: Seu codigo de verificacao Minha Claro e 441092. Valido por 10 minutos." },
    { id: 316, co: "Vivo BR", txt: "Vivo: Use o codigo 772109 para validar seu acesso ao Meu Vivo." },
    { id: 317, co: "TIM BR", txt: "TIM: Seu codigo de seguranca e 552910. Use para acessar o Meu TIM. Nao compartilhe." },
    { id: 318, co: "Oi BR", txt: "Oi: Informe o codigo 110293 para confirmar seu cadastro na Minha Oi." },
    { id: 319, co: "99Taxi", txt: "99: Seu código de verificação é 441092. Informe apenas no aplicativo." },
    { id: 320, co: "Uber BR", txt: "Uber: 882910 e o seu codigo de verificacao. Nunca compartilhe esse codigo." },
    { id: 321, co: "Americanas", txt: "Americanas: Seu codigo de seguranca e 772109. Nao o compartilhe. Boas compras!" },
    { id: 322, co: "Casas Bahia", txt: "Casas Bahia: Use o codigo 552910 para confirmar sua compra. Dedicacao total a voce." },
    { id: 323, co: "Ponto", txt: "Ponto: Informe o codigo 110293 para validar seu acesso ao site." },
    { id: 324, co: "Netshoes", txt: "Netshoes: Seu codigo de verificacao e 882910. Pratique esporte agora!" },
    { id: 325, co: "Zattini", txt: "Zattini: Use o codigo 441092 para confirmar sua conta de moda." },
    { id: 326, co: "Dafiti", txt: "Dafiti: Seu codigo de seguranca e 772109. Valido por 15 minutos." },
    { id: 327, co: "Renner", txt: "Renner: Informe o codigo 552910 para acessar seus cartoes e beneficios." },
    { id: 328, co: "C&A BR", txt: "C&A: Seu codigo de verificacao e 110293. Aproveite as ofertas!" },
    { id: 329, co: "Riachuelo", txt: "Riachuelo: Use o codigo 882910 para validar seu login no App." },
    { id: 330, co: "Pão de Açúcar", txt: "PDA: Informe o codigo 441092 para confirmar sua compra no delivery." },
    { id: 331, co: "Carrefour BR", txt: "Carrefour: Seu codigo de seguranca e 772109. Nao compartilhe." },
    { id: 332, co: "Extra BR", txt: "Extra: Use o codigo 552910 para validar seu cadastro no Clube Extra." },
    { id: 333, co: "LATAM BR", txt: "LATAM: Seu codigo de verificacao e 110293. Tenha um excelente voo!" },
    { id: 334, co: "Azul BR", txt: "Azul: Informe o codigo 882910 para acessar sua conta TudoAzul." },
    { id: 335, co: "Gol BR", txt: "GOL: Use o codigo 441092 para confirmar seu check-in online." },
    { id: 336, co: "Rappi BR", txt: "Rappi: Seu codigo de seguranca e 772109. Nunca pediremos esse codigo por telefone." },
    { id: 337, co: "Loggi", txt: "Loggi: Informe o codigo 552910 para confirmar a entrega do seu pacote." },
    { id: 338, co: "Mercado Pago", txt: "Mercado Pago: Seu codigo de seguranca e 110293. Nao o compartilhe com ninguem." },
    { id: 339, co: "RecargaPay", txt: "RecargaPay: Use o codigo 882910 para validar sua recarga de celular." },
    { id: 340, co: "Ame Digital", txt: "Ame: Seu codigo de verificacao e 441092. Utilize-o para pagar com o App." },
    { id: 341, co: "Elo", txt: "Elo: Use o codigo 772109 para confirmar seu cadastro nos beneficios Elo." },
    { id: 342, co: "Serasa", txt: "Serasa: Informe o codigo 552910 para consultar seu score com seguranca." },
    { id: 343, co: "Boa Vista", txt: "Boa Vista: Seu codigo de verificacao e 110293 para acesso ao portal." },
    { id: 344, co: "QuintoAndar", txt: "QuintoAndar: Use o codigo 882910 para validar seu login de inquilino ou dono." },
    { id: 345, co: "Zap Imóveis", txt: "ZAP: Seu codigo de seguranca e 441092 para contato com o anunciante." },
    { id: 346, co: "OLX BR", txt: "OLX: Informe o codigo 772109 para confirmar seu anuncio. Nao compartilhe." },
    { id: 347, co: "Webmotors", txt: "Webmotors: Use o codigo 552910 para validar sua proposta de carro." },
    { id: 348, co: "Enjoei", txt: "Enjoei: Seu codigo de verificacao e 110293. Boas vendas!" },
    { id: 349, co: "Elo7", txt: "Elo7: Informe o codigo 882910 para confirmar seu pedido artesanal." },
    { id: 350, co: "Hotmart", txt: "Hotmart: Use o codigo 441092 para acessar seu curso digital." },
    { id: 351, co: "Eduzz", txt: "Eduzz: Seu codigo de seguranca e 772109 para acesso a plataforma." },
    { id: 352, co: "Monetizze", txt: "Monetizze: Informe o codigo 552910 para validar sua conta de afiliado." },
    { id: 353, co: "Boticário", txt: "Boticario: Seu codigo de verificacao e 110293. Viva a beleza!" },
    { id: 354, co: "Natura", txt: "Natura: Use o codigo 882910 para confirmar seu pedido de bem estar." },
    { id: 355, co: "Avon BR", txt: "Avon: Informe o codigo 441092 para acessar o portal da consultora." },
    { id: 356, co: "CVC BR", txt: "CVC: Seu codigo de seguranca e 772109 para confirmar sua viagem." },
    { id: 357, co: "Decolar", txt: "Decolar: Use o codigo 552910 para validar sua reserva de hotel." },
    { id: 358, co: "Localiza", txt: "Localiza: Informe o codigo 110293 para confirmar seu aluguel de carro." },
    { id: 359, co: "Movida", txt: "Movida: Seu codigo de verificacao e 882910 para acesso ao App." },
    { id: 360, co: "WhatsApp Business", txt: "<#> Seu codigo do WhatsApp Business e: 441-092. Nao compartilhe." },
  ],
  CN: [
    { id: 401, co: "Alipay", txt: "【支付宝】您的验证码是 552910。验证码30分钟内有效，请勿向任何人提供您的验证码，以免资金被盗。" },
    { id: 402, co: "WeChat", txt: "【WeChat】验证码：882910。请在注册/登录页面输入，切勿泄露给他人。" },
    { id: 403, co: "Baidu", txt: "【百度】验证码为：441092，用于帐号安全验证。若非本人操作，请忽略此短信。" },
    { id: 404, co: "JD.com", txt: "【京东】您的动态验证码是 772109。请确保在官方APP输入，京东员工不会向您索要验证码。" },
    { id: 405, co: "Meituan", txt: "【美团】您的登录验证码为 110293，5分钟内有效。为了您的帐号安全，请勿告知他人。" },
    { id: 406, co: "TikTok/Douyin", txt: "【抖音】您的验证码是 882910。用于手机号登录。验证码请勿泄露。" },
    { id: 407, co: "Taobao", txt: "【淘宝】您的验证码为 441092。请在5分钟内输入。如非本人操作，请关注帐号安全。" },
    { id: 408, co: "Didi", txt: "【滴滴出行】您的验证码是 772109，请勿将验证码告知他人。祝您旅途愉快！" },
    { id: 409, co: "Weibo", txt: "【微博】您的验证码是 552910，打死也不要告诉别人哦！有效时间15分钟。" },
    { id: 410, co: "NetEase", txt: "【网易】验证码 110293，用于网易账号安全认证，3分钟内有效。" },
    { id: 411, co: "Ele.me", txt: "【饿了么】验证码 882910，您正在登录饿了么，请于2分钟内输入。" },
    { id: 112, co: "Pinduoduo", txt: "【拼多多】您的验证码是 441092。非本人操作请忽略。请勿将验证码泄露给他人。" },
    { id: 413, co: "Ctrip", txt: "【携程旅行】您的手机验证码为 772109，请在页面中输入以完成验证。" },
    { id: 414, co: "Bilibili", txt: "【哔哩哔哩】您的登录验证码为 552910，请在20分钟内填写，请勿告诉他人。" },
    { id: 415, co: "IQIYI", txt: "【爱奇艺】验证码 110293。您正在进行身份验证，请妥善保管验证码。" },
    { id: 416, co: "Zhihu", txt: "【知乎】验证码 882910，用于手机号登录，有效期5分钟。" },
    { id: 417, co: "Xiaohongshu", txt: "【小红书】验证码：441092。您正在登录小红书，请勿将验证码告知他人。" },
    { id: 418, co: "China Mobile", txt: "【中国移动】您的随机验证码为 772109，用于业务办理身份验证，请妥善保管。" },
    { id: 419, co: "China Unicom", txt: "【中国联通】您的校验码是 552910，请在页面中输入完成校验，谢谢。" },
    { id: 420, co: "China Telecom", txt: "【中国电信】验证码 110293，请在窗口中输入以确认您的操作。" },
    { id: 421, co: "ICBC", txt: "【工商银行】您的短信认证码为 882910，用于办理网银业务，请勿泄露。" },
    { id: 422, co: "CCB", txt: "【建设银行】您的验证码是 441092，请在5分钟内按页面提示提交。" },
    { id: 423, co: "Bank of China", txt: "【中国银行】您正在办理交易，验证码为 772109，请勿向他人提供。" },
    { id: 424, co: "ABC Bank", txt: "【农业银行】您的动态验证码是 552910，请按照页面提示输入。" },
    { id: 425, co: "China Post", txt: "【中国邮政】验证码 110293，用于邮政业务查询，请勿告知他人。" },
    { id: 426, co: "SF Express", txt: "【顺丰速运】您的验证码为 882910，用于运单查询身份验证。" },
    { id: 427, co: "Keep", txt: "【Keep】验证码 441092。您正在登录Keep，请勿向任何人提供此码。" },
    { id: 428, co: "DingTalk", txt: "【钉钉】验证码 772109，用于登录钉钉，5分钟内有效。转发可能导致帐号被盗。" },
    { id: 429, co: "WPS", txt: "【WPS Office】您的动态验证码是 552910，感谢使用金山办公服务。" },
    { id: 430, co: "Ximalaya", txt: "【喜马拉雅】验证码 110293，请在登录页面输入。听书，听戏，听新闻。" },
    { id: 431, co: "Tencent Video", txt: "【腾讯视频】您的登录验证码是 882910，请在页面中输入完成验证。" },
    { id: 432, co: "Kuaishou", txt: "【快手】您的验证码为 441092，请勿泄露给他人。非本人操作请忽略。" },
    { id: 433, co: "Sohu", txt: "【搜狐】验证码 772109，欢迎回到搜狐。请在10分钟内完成验证。" },
    { id: 434, co: "ByteDance", txt: "【字节跳动】您的动态码为 552910，用于身份校验，请妥善保管。" },
    { id: 435, co: "Migu Music", txt: "【咪咕音乐】验证码 110293，请在音乐播放页面输入完成订购。" },
    { id: 436, co: "Qyer", txt: "【穷游网】您的验证码是 882910，用于重置密码验证，有效期15分钟。" },
    { id: 437, co: "Mafengwo", txt: "【马蜂窝】验证码为 441092。世界尽在指尖，请勿告知他人此码。" },
    { id: 438, co: "AutoNavi", txt: "【高德地图】您的验证码是 772109，用于高德帐号登录验证。" },
    { id: 439, co: "Tuhu", txt: "【途虎养车】验证码 552910，用于车辆保养预约验证。" },
    { id: 440, co: "Luckin Coffee", txt: "【瑞幸咖啡】您的登录验证码为 110293。这一杯，敬自由。" },
    { id: 441, co: "HeyTea", txt: "【喜茶】您的动态码是 882910。请在小程序中输入，享受灵感之茶。" },
    { id: 442, co: "Hema", txt: "【盒马】验证码 441092。您正在登录盒马鲜生，请勿告知他人。" },
    { id: 443, co: "Suning", txt: "【苏宁易购】您的动态验证码是 772109。苏宁易购，放心去喜欢。" },
    { id: 444, co: "GOME", txt: "【国美】验证码 552910，用于国美帐号登录。请妥善保管。" },
    { id: 445, co: "Vipshop", txt: "【唯品会】您的验证码为 110293。品牌特卖，就是超值。" },
    { id: 446, co: "Dangdang", txt: "【当当网】验证码 882910，用于购书账号登录。读书，让我们变美。" },
    { id: 447, co: "Douban", txt: "【豆瓣】验证码 441092，用于豆瓣帐号安全校验。" },
    { id: 448, co: "Huya", txt: "【虎牙直播】您的登录验证码为 772109。看直播，上虎牙。" },
    { id: 449, co: "Douyu", txt: "【斗鱼】验证码 552910，用于斗鱼账号登录验证。" },
    { id: 450, co: "Tencent Cloud", txt: "【腾讯云】您的校验码为 110293。感谢您使用腾讯云服务。" },
    { id: 451, co: "Aliyun", txt: "【阿里云】您的验证码是 882910。用于云服务器管理身份核验。" },
    { id: 452, co: "Huawei Cloud", txt: "【华为云】您的登录验证码为 441092，请在页面输入进行验证。" },
    { id: 453, co: "Lenovo", txt: "【联通】您的验证码是 772109，请在联想官网输入以确认操作。" },
    { id: 454, co: "Haier", txt: "【海尔】您的验证码为 552910。智家生活，从海尔开始。" },
    { id: 455, co: "Gree", txt: "【格力】您的验证码是 110293。好空调，格力造。" },
    { id: 456, co: "Xiaomi", txt: "【小米】您的动态验证码为 882910，用于小米帐号登录，请勿泄露。" },
    { id: 457, co: "OPPO", txt: "【OPPO】验证码 441092，用于OPPO帐号身份核实。" },
    { id: 458, co: "Vivo", txt: "【Vivo】您的动态码是 772109。欢迎使用Vivo账号服务。" },
    { id: 459, co: "ZTE", txt: "【中兴】您的验证码为 552910。用于中兴商城账号验证。" },
    { id: 460, co: "Meizu", txt: "【魅族】验证码 110293。追求源于热爱，请勿告知他人验证码。" },
  ],
  JP: [
    { id: 501, co: "LINE", txt: "LINE 認証番号：882910 この番号を他人に教えないでください。有効期間は30分です。" },
    { id: 502, co: "Rakuten", txt: "【楽天】認証番号は 772109 です。この番号を第三者に教えないでください。有効期間は30分です。" },
    { id: 503, co: "PayPay", txt: "PayPay認証コード：552910（有効期限10分）。このコードを他人に教えないでください。" },
    { id: 504, co: "Mercari", txt: "【メルカリ】認証番号：110293 を入力してください。有効期限は5分です。" },
    {
      id: 505,
      co: "Amazon JP",
      txt: "Amazon：882910は認証コードです。このコードを他人に教えないでください。Amazonが電話で尋ねることはありません。",
    },
    {
      id: 506,
      co: "Sony PSN",
      txt: "Sony PlayStation Network：2段階認証コードは 441092 です。このコードを入力してログインしてください。",
    },
    { id: 507, co: "Nintendo", txt: "ニンテンドーアカウントの認証番号は 772109 です。有効期間は20分です。" },
    { id: 508, co: "Seven Bank", txt: "【セブン銀行】ワンタイムパスワードは 552910 です。この番号を誰にも教えないでください。" },
    { id: 509, co: "Yahoo! Japan", txt: "Yahoo! JAPAN 認証コード：110293（10分間有効）。このコードを誰にも教えないでください。" },
    { id: 510, co: "Sagawa Express", txt: "佐川急便：スマートクラブ認証コードは 882910 です。有効時間は10分です。" },
    { id: 511, co: "Kuroneko Yamato", txt: "ヤマト運輸：クロネコメンバーズの認証コードは 441092 です。大切に保管してください。" },
    { id: 512, co: "Japan Post", txt: "日本郵便：ゆうパックスマホ割の認証番号は 772109 です。30分以内に入力してください。" },
    { id: 513, co: "Softbank", txt: "【ソフトバンク】My SoftBank認証コード：552910。有効期限は15分です。" },
    {
      id: 514,
      co: "docomo",
      txt: "【dアカウント】セキュリティコード：110293。第三者による不正利用を防ぐため、共有しないでください。",
    },
    { id: 515, co: "au", txt: "【au】2段階認証コード：882910。au IDのログインを完了させてください。" },
    { id: 516, co: "Suica", txt: "モバイルSuica：認証コードは 441092 です。この番号を誰にも教えないでください。" },
    { id: 517, co: "Pasmo", txt: "モバイルPASMO：会員登録用の認証番号は 772109 です。" },
    { id: 518, co: "Aeon Bank", txt: "【イオン銀行】ワンタイムパスワードは 552910 です。有効期限内にご入力ください。" },
    { id: 519, co: "Mizuho Bank", txt: "【みずほ銀行】みずほダイレクト認証コード：110293。この番号を他人に伝えないでください。" },
    { id: 520, co: "MUFG Bank", txt: "三菱UFJ銀行：ワンタイムパスワードは 882910 です。第三者へ教えないでください。" },
    { id: 521, co: "Sumitomo Mitsui", txt: "三井住友銀行：ワンタイムパスワードは 441092 です。SMBCダイレクトで入力してください。" },
    { id: 522, co: "SBI Securities", txt: "SBI証券：認証コードは 772109 です。ログインを続行してください。" },
    { id: 523, co: "Nomura", txt: "野村證券：オンラインサービス認証番号は 552910 です。大切に保管してください。" },
    { id: 524, co: "DMM", txt: "DMM.com：認証コードは 110293 です。10分以内に入力してください。" },
    { id: 525, co: "Zozotown", txt: "ZOZOTOWN：認証コード 882910。有効期限は10分です。お買い物をお楽しみください。" },
    { id: 526, co: "Uniqlo Japan", txt: "ユニクロ：オンラインストア認証番号は 441092 です。この番号を他人に教えないでください。" },
    { id: 527, co: "GU Japan", txt: "GUオンライン：認証コード 772109。有効期限内にご入力ください。" },
    { id: 528, co: "Bic Camera", txt: "ビックカメラ：ビックネット認証番号は 552910 です。" },
    { id: 529, co: "Yodobashi", txt: "ヨドバシ・ドット・コム：会員ログイン認証コードは 110293 です。" },
    { id: 530, co: "McDonald's JP", txt: "マクドナルド：認証番号 882910。モバイルオーダーでのご利用ありがとうございます。" },
    { id: 531, co: "Starbucks JP", txt: "スターバックス：My Starbucks認証コード 441092。有効期限は10分です。" },
    { id: 532, co: "Hot Pepper", txt: "ホットペッパーグルメ：予約認証コード 772109。ご来店をお待ちしております。" },
    { id: 533, co: "Tabelog", txt: "食べログ：電話認証番号 552910。この番号を他人に教えないでください。" },
    { id: 534, co: "Uber Eats JP", txt: "Uber Eats：認証コード 110293 を入力して注文を確定させてください。" },
    { id: 535, co: " 出前館", txt: "出前館：ログイン認証コードは 882910 です。美味しい料理をお届けします。" },
    { id: 536, co: "JAL", txt: "日本航空：JMB会員ログイン認証番号は 441092 です。空の旅をお楽しみください。" },
    { id: 537, co: "ANA", txt: "ANA：マイレージクラブ認証番号 772109。有効期限は15分です。" },
    { id: 538, co: "JR East", txt: "JR東日本：えきねっと認証番号 552910。切符の予約を完了してください。" },
    { id: 539, co: "T-Point", txt: "Tポイント：Tサイト認証番号 110293。ポイントの確認はこちらから。" },
    { id: 540, co: "Ponta", txt: "Ponta：PontaWebログイン認証コードは 882910 です。" },
    { id: 541, co: "D-Point", txt: "dポイント：dマーケット認証コード 441092。お得な情報をチェック！" },
    { id: 542, co: "Disney Resport", txt: "東京ディズニーリゾート：予約認証番号 772109。夢の国へようこそ。" },
    { id: 543, co: "USJ Japan", txt: "ユニバーサル・スタジオ・ジャパン：チケット購入認証番号 552910 です。" },
    { id: 544, co: "Recruit", txt: "リクルート：ID連携認証コードは 110293 です。大切に保管してください。" },
    { id: 545, co: "AbemaTV", txt: "ABEMA：デバイス連携コードは 882910 です。大画面で視聴をお楽しみください。" },
    { id: 546, co: "TVer", txt: "TVer：テレビ連携認証番号 441092。見逃し配信をチェック！" },
    { id: 547, co: "U-Next", txt: "U-NEXT：認証コード 772109。映画、ドラマ、アニメをお楽しみください。" },
    { id: 548, co: "Pixiv", txt: "pixiv：認証コード 552910。創作活動を応援しています。" },
    { id: 549, co: "Niconico", txt: "ニコニコ動画：ログイン認証コードは 110293 です。" },
    { id: 550, co: "Gree JP", txt: "GREE：認証コード 882910。ゲームの世界へようこそ。" },
    { id: 551, co: "Mobage", txt: "モバゲー：認証番号 441092。有効期限は10分です。" },
    { id: 552, co: "Cygames", txt: "Cygames：データ連携認証コードは 772109 です。" },
    { id: 553, co: "Square Enix JP", txt: "スクウェア・エニックス：ワンタイムパスワードは 552910 です。" },
    { id: 554, co: "Capcom JP", txt: "カプコンID：認証コード 110293。大切に保管してください。" },
    { id: 555, co: "Sega JP", txt: "セガID：認証番号 882910。ゲームセンターでお待ちしております。" },
    { id: 556, co: "Konami JP", txt: "コナミID：2段階認証コードは 441092 です。" },
    { id: 557, co: "Bandai Namco JP", txt: "バンダイナムコID：認証コード 772109。遊びをクリエイト。" },
    { id: 558, co: "Toyota Connect", txt: "T-Connect：認証番号 552910。安全運転をサポートします。" },
    { id: 559, co: "Honda Connect", txt: "Honda Total Care：認証コード 110293。快適なドライブを。" },
    { id: 560, co: "Nissan Connect", txt: "NissanConnect：ログイン認証番号は 882910 です。" },
  ],
  DE: [
    {
      id: 601,
      co: "Deutsche Bank",
      txt: "Ihre mobileTAN für den Auftrag am 22.12.2025 ist 772109. Bitte prüfen Sie die Empfänger-IBAN vor der Eingabe.",
    },
    {
      id: 602,
      co: "N26",
      txt: "N26: Bestätigen Sie Ihre Anmeldung mit dem Code 110293. Dieser Code ist 5 Minuten gültig. Geben Sie ihn nicht weiter.",
    },
    {
      id: 603,
      co: "Sparkasse",
      txt: "S-pushTAN: Ihre Registrierungsdaten wurden erfolgreich verarbeitet. Geben Sie den Code 882910 in Ihrer App ein.",
    },
    {
      id: 604,
      co: "Commerzbank",
      txt: "Commerzbank: Ihre photoTAN-Aktivierungsgrafik wurde angefordert. Nutzen Sie den Code 441092 zur Bestätigung.",
    },
    {
      id: 605,
      co: "ING Deutschland",
      txt: "ING: Nutzen Sie den Einmalcode 552910 zur Freigabe Ihres Logins. Teilen Sie diesen Code niemals mit Dritten.",
    },
    {
      id: 606,
      co: "PayPal DE",
      txt: "PayPal: Ihr Sicherheitscode lautet 882910. Geben Sie diesen Code nicht an andere Personen weiter.",
    },
    {
      id: 607,
      co: "Telekom",
      txt: "Telekom: Ihr Sicherheits-Code für den Login im Kundencenter ist 110293. Er ist 10 Minuten lang gültig.",
    },
    {
      id: 608,
      co: "Vodafone DE",
      txt: "Vodafone: Ihr SMS-Code für MeinVodafone ist 772109. Geben Sie den Code niemals an andere weiter.",
    },
    { id: 609, co: "O2 DE", txt: "O2: Ihr Einmal-Passwort lautet 552910. Bitte geben Sie es im Portal ein. Ihr O2 Team." },
    {
      id: 610,
      co: "Zalando",
      txt: "Dein Zalando Bestätigungscode lautet 441092. Er ist 15 Minuten lang gültig. Viel Spaß beim Shoppen!",
    },
    {
      id: 611,
      co: "Amazon DE",
      txt: "882910 ist Ihr Amazon-Einmalpasswort. Geben Sie dieses niemals an Dritte weiter. Amazon wird Sie niemals danach fragen.",
    },
    { id: 612, co: "eBay DE", txt: "Guten Tag, Ihr eBay-Sicherheitscode lautet 772109. Er läuft in 15 Minuten ab." },
    { id: 613, co: "Otto", txt: "OTTO: Ihr Code zur Verifizierung Ihres Kontos ist 110293. Wir freuen uns auf Ihre Bestellung." },
    { id: 614, co: "Lidl Plus", txt: "Dein Lidl Plus Verifizierungscode ist 552910. Gib diesen Code bitte in der Lidl Plus App ein." },
    { id: 615, co: "Rewe", txt: "REWE: Dein Code für die Anmeldung bei REWE Karten & Services ist 882910." },
    { id: 616, co: "Check24", txt: "CHECK24: Ihr Bestätigungscode für den Vergleich ist 441092. Vielen Dank für Ihr Vertrauen." },
    { id: 617, co: "StepStone", txt: "StepStone: Ihr Code für den Login ist 772109. Viel Erfolg bei Ihrer Jobsuche!" },
    { id: 618, co: "XING", txt: "XING: Ihr Verifizierungscode lautet 552910. Willkommen zurück in Ihrem Netzwerk." },
    { id: 619, co: "Klarna DE", txt: "Klarna: Dein Einmalcode ist 110293. Teile diesen Code niemals mit anderen Personen." },
    { id: 620, co: "Postbank", txt: "Postbank: Ihre Bestseal-Aktivierung ist fast abgeschlossen. Nutzen Sie den Code 882910." },
    { id: 621, co: "ADAC", txt: "ADAC: Ihr Aktivierungscode für 'Mein ADAC' ist 441092. Er ist 24 Stunden gültig." },
    { id: 622, co: "Deutsche Bahn", txt: "DB: Ihr Code für den Login bei bahn.de ist 772109. Wir wünschen eine gute Reise." },
    { id: 623, co: "Lufthansa", txt: "Lufthansa: Ihr Miles & More Login-Code ist 552910. Er läuft in 15 Minuten ab." },
    { id: 624, co: "FlixBus", txt: "FlixBus: Dein Verifizierungscode ist 110293. Wir sehen uns im Bus!" },
    { id: 625, co: "Sixt", txt: "SIXT: Ihr Code zur Bestätigung Ihrer Identität ist 882910. Vielen Dank für Ihre Reservierung." },
    { id: 626, co: "Lieferando", txt: "Lieferando: Dein Bestätigungscode ist 441092. Guten Appetit!" },
    { id: 627, co: "HelloFresh DE", txt: "HelloFresh: Dein Code zum Anmelden ist 772109. Viel Spaß beim Kochen!" },
    { id: 628, co: "Fielmann", txt: "Fielmann: Ihr Code für die Terminbuchung ist 552910. Wir freuen uns auf Ihren Besuch." },
    { id: 629, co: "Douglas", txt: "Douglas: Dein Code für dein Beauty-Konto ist 110293. Strahle mit uns!" },
    { id: 630, co: "MediaMarkt", txt: "MediaMarkt: Ihr myMediaMarkt Verifizierungscode ist 882910. Viel Spaß mit der Technik." },
    { id: 631, co: "Saturn", txt: "Saturn: Ihr Code für den Technik-Service ist 441092." },
    { id: 632, co: "Hornbach", txt: "HORNBACH: Ihr Code für das Kundenkonto ist 772109. Es gibt immer was zu tun." },
    { id: 633, co: "Bauhaus", txt: "BAUHAUS: Ihr Verifizierungscode ist 552910. Wenn's gut werden muss." },
    { id: 634, co: "Tchibo", txt: "Tchibo: Ihr Code für die Card-Anmeldung ist 110293. Erleben Sie die Welt von Tchibo." },
    { id: 635, co: "Rossmann", txt: "ROSSMANN: Dein Code für die App ist 882910. Wir freuen uns auf dich!" },
    { id: 636, co: "DM Drogerie", txt: "dm-Markt: Dein Verifizierungscode für 'Mein dm' ist 441092." },
    { id: 637, co: "Allianz", txt: "Allianz: Ihr Code für das Portal 'Meine Allianz' ist 772109." },
    { id: 638, co: "HUK-Coburg", txt: "HUK-COBURG: Ihr Bestätigungscode lautet 552910. Sicher informiert." },
    { id: 639, co: "DKB", txt: "DKB: Ihr Registrierungscode für DKB-ID ist 110293. Bitte in der App eingeben." },
    { id: 640, co: "Trade Republic", txt: "Trade Republic: Dein Verifizierungscode ist 882910. Er ist 10 Minuten lang gültig." },
    { id: 641, co: "Scalable Capital", txt: "Scalable: Ihr Code zur Anmeldung ist 441092. Investieren Sie klug." },
    { id: 642, co: "BMW Connected", txt: "BMW: Ihr Sicherheitscode für My BMW ist 772109. Freude am Fahren." },
    { id: 643, co: "Mercedes me", txt: "Mercedes me: Ihr Code zur Anmeldung ist 552910." },
    { id: 644, co: "Volkswagen ID", txt: "VW: Ihr Code für die Volkswagen ID lautet 110293." },
    { id: 645, co: "E.ON", txt: "E.ON: Ihr Code für das Mein E.ON Portal ist 882910." },
    { id: 646, co: "Vattenfall", txt: "Vattenfall: Ihr Verifizierungscode für den Login ist 441092." },
    { id: 647, co: "EnBW", txt: "EnBW: Nutzen Sie den Code 772109 zur Bestätigung Ihrer Anmeldung." },
    { id: 648, co: "Sky Go DE", txt: "Sky: Ihr mobiler Aktivierungscode lautet 552910." },
    { id: 649, co: "DAZN DE", txt: "DAZN: Ihr Bestätigungscode ist 110293. Erlebe deinen Sport live." },
    { id: 650, co: "Disney+ DE", txt: "Disney+: Dein Verifizierungscode lautet 882910. Viel Spaß beim Streamen!" },
    { id: 651, co: "Apple ID DE", txt: "Ihr Apple ID Code lautet 441092. Geben Sie ihn nicht an Dritte weiter." },
    { id: 652, co: "Microsoft DE", txt: "Verwenden Sie 772109 als Sicherheitscode für das Microsoft-Konto." },
    { id: 653, co: "Google DE", txt: "G-552910 ist dein Google-Bestätigungscode. Niemand von Google wird dich danach fragen." },
    { id: 654, co: "Instagram DE", txt: "<#> 110293 ist dein Instagram-Code. Teile ihn nicht mit anderen. SIY992de" },
    { id: 655, co: "Facebook DE", txt: "882910 ist dein Facebook-Code. Teile ihn für deine Sicherheit nicht mit anderen." },
    { id: 656, co: "LinkedIn DE", txt: "Ihr LinkedIn-Sicherheitscode lautet 441092. Er läuft in 10 Minuten ab." },
    { id: 657, co: "Twitter/X DE", txt: "Dein Bestätigungscode für X lautet 772109." },
    { id: 658, co: "Snapchat DE", txt: "Snapchat-Code: 552910. Viel Spaß beim Snappen!" },
    { id: 659, co: "Discord DE", txt: "Dein Discord-Verifizierungscode ist: 110293." },
    { id: 660, co: "WhatsApp DE", txt: "Dein WhatsApp-Code: 882-910. Teile diesen Code niemals mit anderen." },
  ],
  FR: [
    {
      id: 701,
      co: "Société Générale",
      txt: "SOCIETE GENERALE : Le code 772109 permet de valider votre connexion. Ne le transmettez jamais, nos conseillers ne vous le demanderont pas.",
    },
    {
      id: 702,
      co: "BNP Paribas",
      txt: "BNP Paribas : Saisissez le code 110293 pour valider votre opération en ligne. Ce code expire dans 3 minutes.",
    },
    { id: 703, co: "Crédit Agricole", txt: "SécuriPass : Votre code de vérification pour l'ajout d'un bénéficiaire est 882910." },
    {
      id: 704,
      co: "Boursorama",
      txt: "Boursorama : Utilisez le code 441092 pour confirmer votre virement. Ne communiquez jamais ce code.",
    },
    { id: 705, co: "Lydia", txt: "Lydia : 552910 est votre code de sécurité pour valider votre paiement. Ne le partagez à personne." },
    {
      id: 706,
      co: "Doctolib",
      txt: "Doctolib : Votre code de connexion est 882910. Ne partagez pas ce code, nous ne vous le demanderons jamais par téléphone.",
    },
    {
      id: 707,
      co: "Ameli",
      txt: "ameli : Votre code de sécurité est 110293. Il est valable 10 minutes. Ne le communiquez à personne.",
    },
    { id: 708, co: "Impots.gouv", txt: "Impots.gouv : Votre code d'accès pour FranceConnect est 772109. Il expire dans 15 minutes." },
    { id: 709, co: "Orange France", txt: "Orange : Votre code de vérification pour accéder à votre Espace Client est 552910." },
    { id: 710, co: "SFR", txt: "SFR : Votre code de sécurité pour l'Espace Client est 110293. Valable 15 min." },
    { id: 711, co: "Bouygues Telecom", txt: "Bouygues : Utilisez le code 882910 pour valider votre commande. Ne le partagez pas." },
    { id: 112, co: "Free Mobile", txt: "Free : Votre code de vérification est 441092. Il est valable pendant 10 minutes." },
    { id: 713, co: "SNCF Connect", txt: "SNCF Connect : Votre code de connexion est 772109. Bon voyage !" },
    {
      id: 714,
      co: "BlaBlaCar",
      txt: "Votre code de vérification BlaBlaCar est 552910. Il expire dans 15 minutes. Ne le partagez pas.",
    },
    { id: 715, co: "Vinted", txt: "Votre code de vérification Vinted est 110293. Bon shopping sur Vinted !" },
    {
      id: 716,
      co: "Cdiscount",
      txt: "Cdiscount : Votre code OTP est 882910. Saisissez-le sur notre site pour valider votre commande.",
    },
    { id: 717, co: "Fnac", txt: "Fnac : Utilisez le code 441092 pour valider votre achat. Merci de votre confiance." },
    { id: 718, co: "Darty", txt: "Darty : Votre code de confirmation est 772109. Il est valable 10 minutes." },
    { id: 719, co: "La Redoute", txt: "La Redoute : Votre code de sécurité est 552910. À très vite sur notre site !" },
    { id: 720, co: "Veepee", txt: "Veepee : Votre code de validation est 110293. Préparez-vous pour la vente !" },
    { id: 721, co: "Leboncoin", txt: "leboncoin : Votre code de vérification est 882910. Ne le partagez pas." },
    { id: 722, co: "Uber France", txt: "Uber : 441092 est votre code de vérification. Ne partagez jamais ce code." },
    { id: 723, co: "Heetch", txt: "Heetch : Ton code de connexion est 772109. À tout de suite !" },
    { id: 724, co: "Deliveroo FR", txt: "Deliveroo : Votre code de vérification est 552910. Bon appétit !" },
    { id: 725, co: "Uber Eats FR", txt: "Uber Eats : 110293 est votre code de validation pour votre commande." },
    { id: 726, co: "Air France", txt: "Air France : Votre code de sécurité Flying Blue est 882910. Bon vol !" },
    { id: 727, co: "EasyJet FR", txt: "EasyJet : Votre code de confirmation est 441092." },
    { id: 728, co: "Booking FR", txt: "Votre code de vérification Booking.com est 772109. Ne partagez pas ce code." },
    { id: 729, co: "Accor Live", txt: "ALL : Votre code de sécurité est 552910. Profitez de votre séjour." },
    { id: 730, co: "Carrefour FR", txt: "Carrefour : Votre code de validation pour votre commande Drive est 110293." },
    { id: 731, co: "E.Leclerc", txt: "E.Leclerc : Votre code de sécurité est 882910 pour accéder à votre compte." },
    { id: 732, co: "Auchan", txt: "Auchan : Votre code de vérification est 441092. À bientôt en magasin !" },
    { id: 733, co: "Decathlon", txt: "Decathlon : Votre code de connexion est 772109. À fond la forme !" },
    { id: 734, co: "Leroy Merlin", txt: "Leroy Merlin : Votre code de sécurité est 552910. Bon bricolage !" },
    { id: 735, co: "Castorama", txt: "Castorama : Votre code de vérification est 110293." },
    { id: 736, co: "Sephora FR", txt: "Sephora : Votre code de sécurité est 882910. Révélez votre beauté !" },
    { id: 737, co: "Yves Rocher", txt: "Yves Rocher : Votre code de validation est 441092. La cosmétique végétale vous attend." },
    { id: 738, co: "Meetic", txt: "Meetic : Votre code de vérification est 772109. Faites de belles rencontres." },
    { id: 739, co: "Tinder FR", txt: "Ton code Tinder est 552910. Ne le partage pas. @tinder.com #552910" },
    { id: 740, co: "AdopteUnMec", txt: "Adopte : Ton code de connexion est 110293." },
    { id: 741, co: "Canal+", txt: "CANAL+ : Votre code de sécurité est 882910. Bon programme !" },
    { id: 742, co: "Molotov TV", txt: "Molotov : Votre code de connexion est 441092. La télé est à vous." },
    { id: 743, co: "Deezer", txt: "Deezer : Votre code de vérification est 772109. Écoutez sans limite." },
    { id: 744, co: "Qonto", txt: "Qonto : Utilisez le code 552910 pour valider votre connexion à votre compte pro." },
    { id: 745, co: "Alan", txt: "Alan : Votre code de sécurité est 110293 pour accéder à votre mutuelle." },
    { id: 746, co: "Swile", txt: "Swile : Votre code de vérification est 882910. Bon déjeuner !" },
    { id: 747, co: "Back Market", txt: "Back Market : Votre code de validation est 441092. Merci pour la planète !" },
    { id: 748, co: "ManoMano", txt: "ManoMano : Votre code de sécurité est 772109." },
    { id: 749, co: "La Fourchette", txt: "TheFork : Votre code de réservation est 552910. Bon appétit !" },
    { id: 750, co: "Cityscoot", txt: "Cityscoot : Votre code de validation est 110293. Bonne route !" },
    { id: 751, co: "Velib", txt: "Vélib' Métropole : Votre code d'accès est 882910." },
    { id: 752, co: "Google FR", txt: "G-441092 est votre code de validation Google. Ne le communiquez pas." },
    { id: 753, co: "Apple ID FR", txt: "Votre code d'identifiant Apple est 772109. Ne le partagez pas avec d'autres." },
    { id: 754, co: "WhatsApp FR", txt: "<#> Votre code WhatsApp : 552-910. Ne partagez jamais ce code." },
    { id: 755, co: "Instagram FR", txt: "<#> 110293 est votre code Instagram. Ne le partagez pas. SIY992fr" },
    { id: 756, co: "Facebook FR", txt: "882910 est votre code de confirmation Facebook." },
    { id: 757, co: "Microsoft FR", txt: "Utilisez 441092 comme code de sécurité de votre compte Microsoft." },
    { id: 758, co: "LinkedIn FR", txt: "Votre code de sécurité LinkedIn est 772109. Il expire dans 10 minutes." },
    { id: 759, co: "Twitter/X FR", txt: "Votre code de confirmation X est 552910." },
    { id: 760, co: "Snapchat FR", txt: "Code Snapchat : 110293. Amuse-toi bien !" },
  ],
};
